-- 코드를 입력하세요                                     
SELECT FOOD_TYPE, REST_ID, REST_NAME, SELF.FAVORITES
FROM REST_INFO RI
JOIN (
    SELECT MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE        
    ) SELF ON RI.FAVORITES = SELF.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC
;