-- 코드를 입력하세요

  
  SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, COUNT(DISTINCT UI.USER_ID) AS PUCHASED_USERS, ROUND((COUNT(DISTINCT UI.USER_ID) / (SELECT count(*)
FROM USER_INFO UI
WHERE YEAR(UI.JOINED) = '2021')), 1) AS PUCHASED_RATIO
  FROM USER_INFO UI
  LEFT JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
  WHERE YEAR(UI.JOINED) = 2021 AND OS.ONLINE_SALE_ID IS NOT NULL
  GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
  ORDER BY YEAR, MONTH
  ;
  
  

  
  
  
  