-- 코드를 입력하세요
SET @HOUR = -1;

SELECT alltime.HOUR, IFNULL(findtime.COUNT, 0) as COUNT
FROM (SELECT (@HOUR := @HOUR + 1) AS HOUR
FROM ANIMAL_OUTS
WHERE @HOUR < 23) alltime
left JOIN (SELECT HOUR(DATETIME) as HOUR, COUNT(HOUR(DATETIME)) as COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR <= 23
ORDER BY HOUR(DATETIME) ASC) findtime on alltime.HOUR = findtime.HOUR


;



