-- 코드를 입력하세요

# SELECT MP.MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
# FROM MEMBER_PROFILE MP
# JOIN (SELECT MEMBER_ID, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID HAVING COUNT(*) = (SELECT MAX(TEMP.COUNT)
#     FROM (SELECT COUNT(*) as COUNT
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID) as TEMP)) TEMP ON MP.MEMBER_ID = TEMP.MEMBER_ID
# ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC

SELECT MP.MEMBER_NAME, TEMP.REVIEW_TEXT, DATE_FORMAT(TEMP.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN (SELECT MEMBER_ID, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
    FROM REST_REVIEW
    WHERE MEMBER_ID IN (SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID HAVING COUNT(*) = (SELECT MAX(TEMP.COUNT)
    FROM (SELECT COUNT(*) as COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID) as TEMP))) TEMP ON MP.MEMBER_ID = TEMP.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC







;
