-- 코드를 입력하세요
SELECT PD.PRODUCT_CODE, (PD.PRICE * SUM(OFF.SALES_AMOUNT)) AS SALES
FROM PRODUCT PD
JOIN OFFLINE_SALE OFF ON PD.PRODUCT_ID = OFF.PRODUCT_ID
GROUP BY PD.PRODUCT_CODE
ORDER BY SALES DESC, PD.PRODUCT_CODE
;
