-- 코드를 입력하세요

# SELECT O1.USER_ID, O2.PRODUCT_ID
# FROM ONLINE_SALE O1
# JOIN (SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
# GROUP BY USER_ID, SALES_AMOUNT
# HAVING count(*) > 1) O2 ON O1.USER_ID = O2.USER_ID AND O1.PRODUCT_ID = O2.PRODUCT_ID
# ORDER BY USER_ID ASC, PRODUCT_ID DESC;


# SELECT *
# FROM ONLINE_SALE
# ORDER BY USER_ID;

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING count(*) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC
;